### ISSUE TITLE
특수문자 오류

### ISSUE THREAD

**Issue by ptdw0428** [moonshiner22/2015.kau.computer-network.7#5]
특수문자 \naver입력시 \n띄고 aver 입력하는 오류가 생길수있음

**Comment by moonshiner22** [comment]
ㄴㄴㄴ
만약 사용자가 "\naver"라고 입력하면, 실제로는 '\' 'n' 'a' 'v' 'e' 'r' '\n' 이렇게 입력됨!
만약 사용자가 "naver"라고 입력하면, 실제로는 'n' 'a' 'v' 'e' 'r' '\n'이렇게 입력됨!
