### ISSUE TITLE
제군들! 모두 리눅스를 깔으라!!!

### ISSUE THREAD

**Issue by moonshiner22** [moonshiner22/2015.kau.computer-network.7#6]
윈도우에서 server 프로그램을 만들던 도중
socket.bind() 함수가 동작되지 않는 걸 확인했다! ㅜㅜ

그러니, 모두들 가상머신에 리눅스를 설치하라!

**Comment by ptdw0428** [comment]
코드 파이썬 바탕맞죠?

2015-05-24 22:30 GMT+09:00 moonshiner22 notifications@github.com:

**Comment by moonshiner22** [comment]
그렇다! 파이썬2.7 문법으로 작성한 파이썬 코드였다!! ㅜㅜ

**Comment by ptdw0428** [comment]
저희 언제 모이나요??
