### ISSUE TITLE
c언어 < - > Python

### ISSUE THREAD

**Issue by ptdw0428** [moonshiner22/2015.kau.computer-network.7#9]
C언어로 코드를짜면 더 편하지 않을까요?

**Comment by moonshiner22** [comment]
C가 좋은 것 같아요!, 비록 지금 바로 옆에 있지만, 이렇게 댓글로 얘기할래요~!

**Comment by whehddnjsv** [comment]
제생각에도  C언어가 더 친숙하기도 하고 .. 가능하다면 해보고싶어요
